name: CI/CD pipeline

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
        
    steps:
    - uses: actions/checkout@v2

    - name: JDK 11 세팅
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: 그래들 래퍼 실행 권한
      run: chmod +x gradlew

    - name: 빌드
      run: ./gradlew build

    - name: 단위 테스트, 통합 테스트
      run: ./gradlew test
  
    - name: 아티팩트 업로드
      uses: actions/upload-artifact@v2
      with:
        name: demo-app
        path: /home/runner/work/practice-cicd/practice-cicd/demo/build/libs/demo-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: 아티팩트 다운로드
      uses: actions/download-artifact@v2
      with:
        name: demo-app
        path: .

    - name: Decode and set up SSH key
      run: |
        echo "${{ secrets.SERVER_KEY }}" | base64 --decode > key.pem
        chmod 600 key.pem

    - name: EC2에 배포
      run: |
        ssh -i key.pem ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} <<-EOF
          pkill java
          nohup java -jar /demo-app.jar &
          disown
        EOF

    - name: 인수 테스트
      run: |
